apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
data:
  # Адрес для Keycloak, который работает снаружи Docker Desktop
  APP_SECURITY_OAUTH2_ISSUER_URI: "http://host.docker.internal:8080/realms/bank-realm"