apiVersion: apps/v1
kind: Deployment
metadata:
  name: cash-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cash-service
  template:
    metadata:
      labels:
        app: cash-service
    spec:
      containers:
        - name: cash-service
          image: "{{ .Values.cash.image.repository }}:{{ .Values.cash.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8900
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: APP_SECURITY_OAUTH2_ISSUER_URI
              valueFrom: { configMapKeyRef: { name: cash-config, key: APP_SECURITY_OAUTH2_ISSUER_URI } }
            - name: KEYCLOAK_CLIENT_ID
              valueFrom: { configMapKeyRef: { name: cash-config, key: KEYCLOAK_CLIENT_ID } }
            - name: ACCOUNT_SERVICE_PATH
              valueFrom: { configMapKeyRef: { name: cash-config, key: ACCOUNT_SERVICE_PATH } }
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-broker-0.kafka-headless.default.svc.cluster.local:9092"
            - name: APP_SECURITY_ENABLED
              value: "true"
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cash-secret
                  key: KEYCLOAK_CLIENT_SECRET
            - name: LOGSTASH_HOST
              valueFrom:
                configMapKeyRef:
                  name: cash-config
                  key: LOGSTASH_HOST
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: cash-config
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8900
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8900
            initialDelaySeconds: 35