services:
#  postgres:
#    image: postgres:16
#    container_name: postgres
#    environment:
#      POSTGRES_DB: bank
#      POSTGRES_USER: bank
#      POSTGRES_PASSWORD: bank
#    ports:
#      - "5444:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./infra/keycloak/realm-export:/opt/keycloak/data/import

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  jenkins_data:


#  accounts-service:
#    build: ./accounts-service
#    container_name: accounts-service
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#    ports:
#      - "8090:8090"
#    depends_on:
#      - keycloak
#      - postgres
#
#  cash-service:
#    build: ./cash-service
#    container_name: cash-service
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#    ports:
#      - "8900:8900"
#    depends_on:
#      - keycloak
#      - accounts-service
#
#  transfer-service:
#    build: ./transfer-service
#    container_name: transfer-service
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#    ports:
#      - "9800:9800"
#    depends_on:
#
#      - keycloak
#      - accounts-service
#
#  notifications-service:
#    build: ./notifications-service
#    container_name: notifications-service
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#    ports:
#      - "9900:9900"
#    depends_on:
#
#      - keycloak
#
#  api-gateway:
#    build: ./api-gateway
#    container_name: api-gateway
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#    ports:
#      - "8700:8700"
#    depends_on:
#
#      - keycloak
#      - accounts-service
#      - cash-service
#      - transfer-service
#
#  front-ui:
#    build: ./front-ui
#    container_name: front-ui
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#    ports:
#      - "8180:8180"
#    depends_on:
#      - keycloak
#      - api-gateway
#
#volumes:
#  postgres_data: