server:
  port: 8700

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: accounts-service-route
          uri: http://accounts-service:8090
          predicates:
            - Path=/accounts/**
        - id: cash-service-route
          uri: http://cash-service:8900
          predicates:
            - Path=/cash/**
        - id: transfer-service-route
          uri: http://transfer-service:9800
          predicates:
            - Path=/transfer/**
        - id: notifications-service-route
          uri: http://notifications-service:9900
          predicates:
            - Path=/notifications/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_SECURITY_OAUTH2_ISSUER_URI}

management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_PATH}