server:
  port: 8700

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: accounts-service-route
          uri: http://localhost:8090
          predicates:
            - Path=/accounts/**

        - id: cash-service-route
          uri: http://localhost:8900
          predicates:
            - Path=/cash/**

        - id: transfer-service-route
          uri: http://localhost:9800
          predicates:
            - Path=/transfer/**
        - id: notifications-service-route
          uri: http://localhost:9900
          predicates:
            - Path=/notifications/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/bank-realm
management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans