spring:
  application:
    name: cash-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_SECURITY_OAUTH2_ISSUER_URI}
      client:
        registration:
          keycloak:
            client-id: ${KEYLOACK_CLIENT_ID}
            client-secret: ${KEYLOACK_CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${APP_SECURITY_OAUTH2_ISSUER_URI}

account:
  service:
    path: http://accounts-service

notification:
  service:
    path: http://notifications-service

server:
  port: 8900

management:
  endpoints:
    web:
      exposure:
        include: health,info