spring:
  application:
    name: cash-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_SECURITY_OAUTH2_ISSUER_URI}
      client:
        registration:
          keycloak:
            client-id: ${KEYLOACK_CLIENT_ID}
            client-secret: ${KEYLOACK_CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${APP_SECURITY_OAUTH2_ISSUER_URI}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        spring.json.add.type.headers: true

account:
  service:
    path: http://accounts-service

server:
  port: 8900

management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_PATH}