account:
  service:
    path:
      http://accounts-service

spring:
  application:
    name: cash-service
  cloud:
    consul:
      host: localhost
      port: 8500
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm
      client:
        registration:
          keycloak:
            client-id: cash-id
            client-secret: GbMK0I9cl5t89lod3Xf47ikldUotRspQ
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bank-realm
server:
  port: 8900

notification:
  service:
    path: http://notifications-service