global:
  scrape_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8700' ]
        labels:
          application: 'api-gateway'

  - job_name: 'accounts-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8090' ]
        labels:
          application: 'accounts-service'

  - job_name: 'cash-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8900' ]
        labels:
          application: 'cash-service'

  - job_name: 'notifications-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:9900' ]
        labels:
          application: 'notifications-service'

  - job_name: 'transfer-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:9800' ]
        labels:
          application: 'transfer-service'