apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  APP_SECURITY_OAUTH2_ISSUER_URI: "http://host.docker.internal:8181/realms/bank-realm"

  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://host.docker.internal:9411/api/v2/spans"

  LOGSTASH_HOST: "host.docker.internal"