spring:
  application:
    name: transfer-service
  cloud:
    consul:
      host: localhost
      port: 8500
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm
      client:
        registration:
          keycloak:
            client-id: transfer-id
            client-secret: 47pOpBWwsoNL8wP6O5XftmBTwH5flif8
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bank-realm

server:
  port: 9800

account:
  service:
    path: http://accounts-service