spring:
  application:
    name: transfer-service
  cloud:
    consul:
      host: localhost
      port: 8500
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm
      client:
        registration:
          keycloak:
            client-id: transfer-id
            client-secret: 47pOpBWwsoNL8wP6O5XftmBTwH5flif8
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bank-realm
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        spring.json.add.type.headers: true

server:
  port: 9800

account:
  service:
    path: http://accounts-service
