spring:
  application:
    name: notifications-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_SECURITY_OAUTH2_ISSUER_URI}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: notifications-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.B0cka.events"

server:
  port: 9900

management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_PATH}
app:
  security:
    enabled: false