spring:
  application:
    name: notifications-service
  cloud:
    consul:
      host: consul
      port: 8500
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/bank-realm

server:
  port: 9900