spring:
  application:
    name: notifications-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notifications-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.B0cka.events"

server:
  port: 9900