api-gateway-charm:
  apiGateway:
    image:
      repository: my-bank-app-api-gateway
      tag: v7

accounts:
  accounts:
    image:
      repository: my-bank-app-accounts-service
      tag: v8

cash:
  cash:
    image:
      repository: my-bank-app-cash-service
      tag: v8

transfer:
  transfer:
    image:
      repository: my-bank-app-transfer-service
      tag: v8

notifications:
  notifications:
    image:
      repository: my-bank-app-notifications-service
      tag: v8