server:
  port: 8180

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/bank-realm/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/bank-realm/protocol/openid-connect/token
            jwk-set-uri: http://localhost:8080/realms/bank-realm/protocol/openid-connect/certs
        registration:
          keycloak:
            authorizationGrantType: authorization_code
            provider: keycloak
            client-id: front-ui
            client-secret: 7jFtkFDPElGOxRzfRUWJTsT8q2XheMnS
            redirect-uri: "http://localhost:8180/accounts"
            scope: openid, profile, email